spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service-route
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
        - id: product-service-route
          uri: lb://product-service
          predicates:
            - Path=/api/v1/products/**, /api/v1/categories/** , /api/v1/images/**
        - id: stock-service-route
          uri: lb://stock-service
          predicates:
            - Path=/api/v1/stock/**
        - id: order-service-route
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**, Path=/api/admin/orders/**


eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true