server:
  port: 8081

spring:
  application:
    name: auth-service

  config:
    import: optional:configserver:http://localhost:8888

  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 693221117307-ren5thjbfi1t7n9llu5bcobh29a2c78b.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          facebook:
            client-id: 1222918276095862
            client-secret: 809b23b99e263c3174a946397c7783e4
            scope:
              - email
              - public_profile

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

app:
  jwt:
    secret: Ntu0p1j??AX,{oW5lLbkR6,):$ct,3.V|?^*dg^P6eo1ddYE>Iqpv#T9Sko:Ko}
    accessTokenExpirationMs: 3600000
    refreshTokenExpirationMs: 86400000

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      retries: 3
      batch-size: 16384
      buffer-memory: 33554432
      properties:
        spring.json.trusted.packages: "com.enaya.service.auth.domain.events"
