server:
  port: 8082

# Database Configuration
spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://postgres-product:5432/product_db
    username: postgres
    password: "0000"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  elasticsearch:
    uris: http://localhost:9200
    username: elastic
    password: pbIM1uTwqFm=Igi7btdc
    connection-timeout: 1s
    socket-timeout: 30s
    ssl:
      verification-mode: none
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterWrite=600s
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: product-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.json.trusted.packages: com.enaya.product_service.infrastructure.messaging.dto
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

# Kafka Topics Configuration
kafka:
  topics:
    products: product-events
    categories: category-events
    collections: collection-events
    stock-updates: stock-updates
    product-events: product-events

# Outbox Pattern Configuration
outbox:
  batch-size: 100
  max-retries: 3
  processor:
    fixed-delay: 5000
    retry-delay: 300000

# AWS S3 Configuration
aws:
  s3:
    access-key: AKIAVWRAY3KFGDXYO2SN
    secret-key: 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
    region: eu-north-1
    bucket: enaya
    endpoint: https://s3.amazonaws.com

# Elasticsearch Configuration
elasticsearch:
  index:
    prefix: product_
  search:
    max-results: 100
    default-page-size: 20
  client:
    username: elastic
    password: pbIM1uTwqFm=Igi7btdc
    connection-timeout: 1s
    socket-timeout: 30s
    ssl:
      verification-mode: none

# Image Processing Configuration
image:
  processing:
    max-file-size: 10MB
    allowed-formats:
      - jpg
      - jpeg
      - png
      - gif
      - webp
      - svg
    thumbnail:
      width: 200
      height: 200
    preview:
      width: 800
      height: 800
    quality: 0.8
    compression:
      enabled: true
      level: 0.7

# Product Service Specific Configuration
product:
  service:
    cache:
      enabled: true
      ttl: 3600
    validation:
      min-name-length: 3
      max-name-length: 255
      min-description-length: 10
      max-description-length: 1000

app:
  jwt:
    secret: sUOHfk58sleuzoFJB7u6wPcC7kRKfyHT/S9vv1BMJ+SCa6GRr/cVFftHMhShsWHxno/dDaQ1BGKiaItYjOn3mw==
    accessTokenExpirationMs: 3600000 # 1 hour
    refreshTokenExpirationMs: 86400000 # 24 hours

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

logging:
  level:
    com.enaya.product_service.config: DEBUG
    io.jsonwebtoken: DEBUG


    org.hibernate: DEBUG
    #org.springframework.transaction: DEBUG
    com.enaya.product_service: DEBUG