spring:
  # Override database configuration for local development
  datasource:
    url: jdbc:h2:mem:stockdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      connection-timeout: 20000
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 300000
      max-lifetime: 1200000
      auto-commit: false
      pool-name: StockHikariPool

  # JPA configuration for H2
  jpa:
    database: H2
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
        generate_statistics: false
        temp:
          use_jdbc_metadata_defaults: false

  # H2 Console
  h2:
    console:
      enabled: true
      path: /h2-console

  # Disable Flyway for H2 development
  flyway:
    enabled: false

  # Disable Kafka for local development
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: stock-service-dev
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "com.enaya.stock_microservice.Domain.event"
        spring.json.use.type.headers: false

# Axon configuration for local development
axon:
  serializer:
    general: jackson
    events: jackson
    messages: jackson
  axonserver:
    enabled: false
  eventstore:
    type: jpa

# Logging for development
logging:
  level:
    com.enaya.stock_microservice: DEBUG
    org.axonframework: INFO
    org.springframework.kafka: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE